#:schema node_modules/wrangler/config-schema.json
name = "bknd-cf-worker-example"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
minify = true

[observability]
enabled = true

[site]
bucket = "../../app/dist/static"